{% set name = "archive-tar-minitar" %}
{% set version = "0.6.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 503985a7f7174fd12f26cae5cfc607a4a625c79a253462b7238b1052cafd9563

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name|replace('-','/') }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: BSD-2-Clause
  license_family: BSD
  license_file: Copyright
  summary: Archive::Tar::Minitar is a pure-Ruby library and command-line utility that provides the ability to deal with POSIX tar(1) archive files

  doc_url: https://www.rubydoc.info/gems/{{ name }}

extra:
  recipe-maintainers:
    - conda-forge/ruby
    - pierrsc
