travis:
  secure:
    BINSTAR_TOKEN: IPZ+CIT9xynhN435nXHp7zCMcQHb6AJI2J+5VAMzG1D70aQmMvi7enbQeLV1VR1Jn1OPpzcaVj0ujH1NUJ3RgF0wtznog+goU3cLUuyM2l92PZ1H7v/loBBoWvlfS9fdQP3S6L2+diAiIHusE5657OVR+CX1Js/wtltsKTP+nfJapptMzjlQowRgTrdfHi1kWcfVlAZuRozIlr4VtD32Yf8Ka4zWRzkmAwxrXgYvtCxD//wqoAvsyAGPcuwdFG17HbBJsXx7PwECij8bFGrCEHrSfheFoKHua1gCwSA6Wq5Eegbqvs9ibTqIzjtwgPwStnoakb+x4TDIzTjBnsHE7Kk3Mt4M9bndkO7NV1+C0lOJZhWp2WJNljC7bGaLN/EIrtMPZUUZ9P3OAZ+CXM6W4cPMZI2H2kIq/IQN6EEPSoekfAtNqaBQ4M6UNkABYw2PaDzrEAxSTHsJbx6aV3hM1ApZi9Pb6xNJRUdkyEt3L7QVXyvPL0nRM6WzfmIIDbnVjCZadWsnI/frd1Guhd+F+7P+xm6ECkZe8YmnBME0WDgQt29ffMl1PCUga2v5SsDpmzAb8M/lwRPzqgSqBOIyFLutucFSZwVtRO2c/ptrskNaK5iZ4eFqPxUZjEc6Bc/GXrx7OxAINhvjnH5nVEQFFxFXMS9RdDS8dLiiH83TEsE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
